/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as JobPrepRouteImport } from './routes/job-prep'
import { Route as LearningPlanRouteImport } from './routes/learning-plan'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as SkillGapRouteImport } from './routes/skill-gap'
import { Route as SkillsRouteImport } from './routes/skills'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JobPrepRoute = JobPrepRouteImport.update({
  id: '/job-prep',
  path: '/job-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningPlanRoute = LearningPlanRouteImport.update({
  id: '/learning-plan',
  path: '/learning-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillGapRoute = SkillGapRouteImport.update({
  id: '/skill-gap',
  path: '/skill-gap',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/job-prep': typeof JobPrepRoute
  '/learning-plan': typeof LearningPlanRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/skill-gap': typeof SkillGapRoute
  '/skills': typeof SkillsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/job-prep': typeof JobPrepRoute
  '/learning-plan': typeof LearningPlanRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/skill-gap': typeof SkillGapRoute
  '/skills': typeof SkillsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/job-prep': typeof JobPrepRoute
  '/learning-plan': typeof LearningPlanRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/skill-gap': typeof SkillGapRoute
  '/skills': typeof SkillsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/assistant'
    | '/dashboard'
    | '/job-prep'
    | '/learning-plan'
    | '/profile'
    | '/recommendations'
    | '/skill-gap'
    | '/skills'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/assistant'
    | '/dashboard'
    | '/job-prep'
    | '/learning-plan'
    | '/profile'
    | '/recommendations'
    | '/skill-gap'
    | '/skills'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/assistant'
    | '/dashboard'
    | '/job-prep'
    | '/learning-plan'
    | '/profile'
    | '/recommendations'
    | '/skill-gap'
    | '/skills'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  AssistantRoute: typeof AssistantRoute
  DashboardRoute: typeof DashboardRoute
  JobPrepRoute: typeof JobPrepRoute
  LearningPlanRoute: typeof LearningPlanRoute
  ProfileRoute: typeof ProfileRoute
  RecommendationsRoute: typeof RecommendationsRoute
  SkillGapRoute: typeof SkillGapRoute
  SkillsRoute: typeof SkillsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-prep': {
      id: '/job-prep'
      path: '/job-prep'
      fullPath: '/job-prep'
      preLoaderRoute: typeof JobPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-plan': {
      id: '/learning-plan'
      path: '/learning-plan'
      fullPath: '/learning-plan'
      preLoaderRoute: typeof LearningPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-gap': {
      id: '/skill-gap'
      path: '/skill-gap'
      fullPath: '/skill-gap'
      preLoaderRoute: typeof SkillGapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  AssistantRoute: AssistantRoute,
  DashboardRoute: DashboardRoute,
  JobPrepRoute: JobPrepRoute,
  LearningPlanRoute: LearningPlanRoute,
  ProfileRoute: ProfileRoute,
  RecommendationsRoute: RecommendationsRoute,
  SkillGapRoute: SkillGapRoute,
  SkillsRoute: SkillsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
